name: adaptive_latents
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytest
  - pandas
  - ffmpeg
  - jupyter
  - h5py
  - pynwb
  - scikit-image
  - coverage
  - dandi
  - fsspec
  - requests
  - aiohttp
  - datahugger
  - numba # todo: this is for mmica, do I really need it?
  - pip
  - pip:
     - jax
     - datahugger
     - "git+https://github.com/Jonathan-Gould/mmica"
#  - jax
#  - jaxlib
