name: adaptive_latents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - ipympl
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytest
  - pytest-xdist
  - pytest-timeout
  - nbval
  - pandas
  - ffmpeg
  - jupyter
  - h5py
  - pynwb
  - scikit-image
  - adjustText
  - coverage
  - yapf
  - dandi
  - fsspec
  - requests
  - aiohttp
  - frozendict
  - pims
  - numba # todo: this is for mmica, do I really need it?
  - av
  - nbstripout
  - pip
  - pip:
     - jax[cuda12]
     - jaxlib
     - datahugger
     - python-picard
     - "git+https://github.com/Jonathan-Gould/mmica"
     - "git+https://github.com/catniplab/vjf.git@0eec61e91c29cf9a44b48c2a6694234b4404a2b3"
#     - matlabengine # todo: this might be removable
     # cd /usr/local/MATLAB/R*/extern/engines/python && pip install .
