name: adaptive_latents
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytest
  - pytest-cov
  - pandas
  - ffmpeg
  - jupyter
  - h5py
  - pynwb
  - scikit-image
#  - jax
#  - jaxlib
