name: adaptive_latents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytest
  - pytest-xdist
  - nbval
  - pandas
  - ffmpeg
  - jupyter
  - h5py
  - pynwb
  - scikit-image
  - adjustText
  - coverage
  - yapf
  - dandi
  - fsspec
  - requests
  - aiohttp
  - frozendict
  - numba # todo: this is for mmica, do I really need it?
  - pip
  - pip:
     - jax
     - jaxlib
     - datahugger
     - python-picard
     - "git+https://github.com/Jonathan-Gould/mmica"
     - matlabengine # todo: this might be removable
     # cd /usr/local/MATLAB/R*/extern/engines/python && pip install .
