name: adaptive_latents
channels:
  - conda-forge
  - defaults
dependencies:
  - jax
  - jaxlib
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytest
  - pytest-cov
  - pandas
  - ffmpeg
  - jupyter
  - h5py
  - pynwb
  - scikit-image
  - adjustText