name: adaptive_latents
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - pyyaml
  - pytest
  - pytest-xdist
  - nbval
  - pandas
  - ffmpeg
  - jupyter
  - h5py
  - pynwb
  - scikit-image
  - adjustText
  - coverage
  - yapf
  - dandi
  - fsspec
  - requests
  - aiohttp
  - frozendict
  - numba # todo: this is for mmica, do I really need it?
  - pip
  - pip:
     - jax
     - jaxlib
     - datahugger
     - matlabengine # todo: this might be removable
     - python-picard
     - "git+https://github.com/Jonathan-Gould/mmica"