import yaml


def to_tex_command(key, value):
    return f"\\expandafter\\newcommand\\csname param-{key}\\endcsname{{{value}}}\n"

if __name__ == '__main__':
    import argparse
    import pathlib
    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", type=pathlib.Path, required=True)
    parser.add_argument("-i", "--input", nargs="+", type=pathlib.Path, required=True)
    args = parser.parse_args()


    with open(args.output, 'w') as output_fhan:
        output_fhan.write(f'% this file is automatically generated\n\n')
        for file in args.input:
            file: pathlib.Path
            match file.suffix:
                case ".yaml":
                    with open(file, 'r') as input_fhan:
                        file_values = yaml.safe_load(input_fhan)
                        if file_values is not None:
                            output_fhan.write(f'% constants loaded from {file}\n')
                            for key, value in file_values.items():
                                output_fhan.write(to_tex_command(key, value))
                case ".tex":
                    output_fhan.write(f'\\input{{{file}}} \n')
                case _:
                    raise Exception(f'unsupported file type: {file}')

            output_fhan.write('\n')
        output_fhan.write(r'\newcommand{\param}[1]{\csname param-#1\endcsname}')
